# Generated by Django 2.1.7 on 2022-05-30 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220530_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 30, 9, 35, 57, 737493)),
        ),
    ]
